import os
from pathlib import Path

# ─── MQTT ────────────────────────────────────────────────────────────────────
MQTT_BROKER = os.getenv("MQTT_BROKER", "localhost")
MQTT_PORT   = int(os.getenv("MQTT_PORT", "1883"))

# ─── Blockchain ──────────────────────────────────────────────────────────────
RPC_URL          = os.getenv("RPC_URL", "http://127.0.0.1:8545")
# Hardhat's first deployment address on a fresh local chain.
CONTRACT_ADDRESS = os.getenv("CONTRACT_ADDRESS", "0x5FbDB2315678afecb367f032d93F642f64180aa3")

# Path to compiled contract ABI (generated by `npx hardhat compile`)
ARTIFACTS_PATH = (
    Path(__file__).parent.parent
    / "artifacts" / "contracts" / "DroneRegistry.sol" / "DroneRegistry.json"
)

# Set DEPLOYER_PRIVATE_KEY in your .env file (see .env.example).
# For local Hardhat dev, use Account #0 printed by `npx hardhat node`.
# Fallback key is Hardhat Account #0 and is ONLY for local development.
DEPLOYER_PRIVATE_KEY = os.getenv(
    "DEPLOYER_PRIVATE_KEY",
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
)

# ─── Simulation ───────────────────────────────────────────────────────────────
TICK_INTERVAL        = 0.5   # seconds between position updates
NODE_TRIGGER_RADIUS_KM = 0.4 # km - how close a drone must be to trigger a node log


