import os
from pathlib import Path

# ─── MQTT ────────────────────────────────────────────────────────────────────
MQTT_BROKER = os.getenv("MQTT_BROKER", "localhost")
MQTT_PORT   = int(os.getenv("MQTT_PORT", "1883"))

# ─── Blockchain ──────────────────────────────────────────────────────────────
RPC_URL          = os.getenv("RPC_URL", "http://127.0.0.1:8545")
CONTRACT_ADDRESS = os.getenv("CONTRACT_ADDRESS", "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266")

# Path to compiled contract ABI (generated by `npx hardhat compile`)
ARTIFACTS_PATH = (
    Path(__file__).parent.parent
    / "artifacts" / "contracts" / "DroneRegistry.sol" / "DroneRegistry.json"
)

# Set DEPLOYER_PRIVATE_KEY in your .env file (see .env.example).
# For local Hardhat dev, use Account #0 printed by `npx hardhat node`.
DEPLOYER_PRIVATE_KEY = os.getenv("DEPLOYER_PRIVATE_KEY", "")

# ─── Simulation ───────────────────────────────────────────────────────────────
TICK_INTERVAL        = 0.5   # seconds between position updates
NODE_TRIGGER_RADIUS_KM = 0.4 # km - how close a drone must be to trigger a node log

